### ISSUE TITLE
Cannot use `fail_point!` 3 arguments macro without importing it

### ISSUE THREAD

**Issue by slinkydeveloper** [tikv/fail-rs#64]
**Describe the bug**
Cannot use full name qualification for `fail_point!` macro in the 3 arguments case

**To Reproduce**
Just try to compile:

```
fail::fail_point!("fail-point-3", enable, |_| {});
```

And you'll get:

```
error: cannot find macro `fail_point` in this scope
   --> my_code.rs:10
    |
10 |                     fail::fail_point!("fail-point-3", enable, |_| {});
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: consider importing this macro:
            fail::fail_point
    = note: this error originates in the macro `fail::fail_point` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Expected behavior**
You should be able to use the macro without importing it with `use`

**Additional context**
Looks like the issue is here: https://github.com/tikv/fail-rs/blob/6645f1767b4d0adbe454a07c25e30224b1b08dbd/src/lib.rs#L841

The recursive macro invocation should look like this:

```rust
$crate::fail_point!($name, $e);
```

**Comment by BusyJay** [comment]
Good catch! Would you like to send a PR to fix it?

**Comment by slinkydeveloper** [comment]
Hi @BusyJay, here is the PR: https://github.com/tikv/fail-rs/pull/66

**Comment by slinkydeveloper** [comment]
Hi @BusyJay, is there any plan to release a new version of this crate? There's a bunch of fixes since the last release :)

**Comment by slinkydeveloper** [comment]
Thank you @BusyJay for the release!
